# Generated by Django 4.0.4 on 2022-05-25 00:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'pagina', 'verbose_name_plural': 'paginas'},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=20, unique=True, verbose_name='URL amigable'),
        ),
    ]
